### ISSUE TITLE
ThinBeam1D

### ISSUE THREAD

**Issue by Batmanabcdefg** [SIMOGroup/SIMO-Package#3]
is the exact solution in ThinBeam1D.m correct?

Best

**Comment by SIMOGroup** [comment]
The exact solution is correct for two separate load cases, that are point and distributed forces. However, since the default code is implemented in a combination of these two load cases, the obtained results are not matched with the exact solution. I have modified the code to make it clearer. Thanks for looking at it.

**Comment by Batmanabcdefg** [comment]
thank you! ,:)
